### ISSUE TITLE
Got error

### ISSUE THREAD

**Issue by biwiwijaya** [Singh-Shivani/Food_Lab#4]
Hei, i very like your app, but i got error, i was followed your step on update document, can you help me for this error?
![error](https://user-images.githubusercontent.com/73777248/97800206-5333b080-1c2b-11eb-9437-c98a601bf301.jpg)

**Comment by Singh-Shivani** [comment]
Hey, can you show me the whole code where error has occurred, and also the
output in terminal(problems).

**Comment by biwiwijaya** [comment]
message_code.dart:

Exception has occurred.
PlatformException (PlatformException(error, Invalid document reference. Document references must have an even number of segments, but users has 1, null, java.lang.IllegalArgumentException: Invalid document reference. Document references must have an even number of segments, but users has 1
	at com.google.firebase.firestore.DocumentReference.forPath(com.google.firebase:firebase-firestore@@21.3.0:80)
	at com.google.firebase.firestore.FirebaseFirestore.document(com.google.firebase:firebase-firestore@@21.3.0:249)
	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin.getDocumentReference(CloudFirestorePlugin.java:124)
	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin.onMethodCall(CloudFirestorePlugin.java:904)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loop(Looper.java:183)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
))


Debug Console :

Launching lib\main.dart on sdk gphone x86 arm in debug mode...
lib\main.dart:1
Parameter format not correct -
√ Built build\app\outputs\flutter-apk\app-debug.apk.
I/FA      ( 8220): Tag Manager is not found and thus will not be used
I/OpenGLRenderer( 8220): Davey! duration=964ms; Flags=1, IntendedVsync=677983077100, Vsync=677983077100, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=677991233400, AnimationStart=677991254500, PerformTraversalsStart=677991277000, DrawStart=678831414300, SyncQueued=678833525000, SyncStart=678835233000, IssueDrawCommandsStart=678836512800, SwapBuffers=678851049600, FrameCompleted=678949224900, DequeueBufferDuration=29297800, QueueBufferDuration=28334800, GpuCompleted=72904454231491230,
I/Choreographer( 8220): Skipped 57 frames!  The application may be doing too much work on its main thread.
W/freelancingfix( 8220): Verification of void com.google.android.gms.internal.measurement.zzb.zza(android.os.Parcel, android.os.IInterface) took 208.561ms (71.92 bytecodes/s) (912B approximate peak alloc)
Connecting to VM Service at ws://127.0.0.1:57949/a2e2yccNM8U=/ws
D/skia    ( 8220): Shader compilation error
D/skia    ( 8220): ------------------------
D/skia    ( 8220): Errors:
D/skia    ( 8220):
D/skia    ( 8220): Shader compilation error
D/skia    ( 8220): ------------------------
D/skia    ( 8220): Errors:
D/skia    ( 8220):
D/skia    ( 8220): Shader compilation error
D/skia    ( 8220): ------------------------
D/skia    ( 8220): Errors:
D/skia    ( 8220):
D/skia    ( 8220): Shader compilation error

**Comment by biwiwijaya** [comment]
I/TetheringManager( 8220): registerTetheringEventCallback:com.biwi.freelancingfix2
W/DynamiteModule( 8220): Local module descriptor class for providerinstaller not found.
I/DynamiteModule( 8220): Considering local module providerinstaller:0 and remote module providerinstaller:0
W/ProviderInstaller( 8220): Failed to load providerinstaller module: No acceptable module found. Local version is 0 and remote version is 0.
I/freelancingfix( 8220): The ClassLoaderContext is a special shared library.
I/chatty  ( 8220): uid=10153(com.biwi.freelancingfix2) AsyncTask #1 identical 1 line
I/freelancingfix( 8220): The ClassLoaderContext is a special shared library.
D/nativeloader( 8220): classloader namespace configured for unbundled product apk. library_path=/product/priv-app/PrebuiltGmsCore/lib/x86:/product/priv-app/PrebuiltGmsCore/PrebuiltGmsCore.apk!/lib/x86:/product/lib:/system/product/lib
W/freelancingfix( 8220): Accessing hidden field Ldalvik/system/BaseDexClassLoader;->pathList:Ldalvik/system/DexPathList; (greylist, reflection, allowed)
W/freelancingfix( 8220): Accessing hidden field Ldalvik/system/DexPathList;->nativeLibraryDirectories:Ljava/util/List; (greylist, reflection, allowed)
W/freelancingfix( 8220): Accessing hidden field Ldalvik/system/DexPathList;->systemNativeLibraryDirectories:Ljava/util/List; (greylist, reflection, allowed)
W/freelancingfix( 8220): Accessing hidden field Ldalvik/system/DexPathList;->nativeLibraryPathElements:[Ldalvik/system/DexPathList$NativeLibraryElement; (greylist, reflection, allowed)
W/freelancingfix( 8220): Accessing hidden method Ldalvik/system/DexPathList;->makePathElements(Ljava/util/List;)[Ldalvik/system/DexPathList$NativeLibraryElement; (greylist, reflection, allowed)
V/NativeCrypto( 8220): Registering com/google/android/gms/org/conscrypt/NativeCrypto's 286 native methods...
W/freelancingfix( 8220): Accessing hidden method Ljava/security/spec/ECParameterSpec;->getCurveName()Ljava/lang/String; (greylist, reflection, allowed)

**Comment by biwiwijaya** [comment]
for all debuging 

[erorrr.txt](https://github.com/Singh-Shivani/Food_Lab/files/5470680/erorrr.txt)

**Comment by Singh-Shivani** [comment]
Check this - https://stackoverflow.com/questions/61967478/document-references-must-have-an-even-number-of-segments-in-flutter
