### ISSUE TITLE
Firebase data

### ISSUE THREAD

**Issue by Safras15** [Singh-Shivani/Food_Lab#8]

**Comment by Safras15** [comment]
@Singh-Shivani can you please provide me the firebase demo data??

**Comment by Singh-Shivani** [comment]
Hi @Safras15,
I'm extremely sorry for late reply, is this requirement over or do you want data?

**Comment by Safras15** [comment]
It's over Shivani.
Thank You..

**Comment by Singh-Shivani** [comment]
Hi @Safras15 ,
Thanks! Let me know if anything else required.
